# Wybierz obraz bazowy z Node.js do uruchomienia aplikacji
FROM my-typescript-app-build:error
# Ekspozycja portu, na którym będzie działać aplikacja
EXPOSE 3000

# Uruchom aplikację
CMD ["yarn", "dev"]
