# Wybierz obraz bazowy z Node.js do uruchomienia aplikacji
FROM my-typescript-app-build

# Ekspozycja portu, na którym będzie działać aplikacja
EXPOSE 3000

CMD errorrrr

# Uruchom aplikację
CMD ["yarn", dev"]
